### ISSUE TITLE
error: unlock of never locked key

### ISSUE THREAD

**Issue by jba** [golang/oscar#13]
From GCP's error reporting API:
panic: "unlock of never locked key" key="\x01github.EventWatcher\x00\x00\x01githubdocs\x00\x00"

See https://pantheon.corp.google.com/errors/detail/CPzSnsKwn7b7-wE;service=gaby-prod;time=P1D?project=oscar-go-1.

**Comment by jba** [comment]
Possibly related: "timed.Watcher already locked"
https://pantheon.corp.google.com/logs/query;cursorTimestamp=2024-09-09T10:04:23.418027Z;endTime=2024-09-09T12:50:40.308592Z;query=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22gaby-prod%22%0Aseverity%3E%3DWARNING%0Atimestamp%3D%222024-09-09T10:00:22Z%22%0AinsertId%3D%2266dec736000236dfc9e9ae49%22;startTime=2024-09-09T05:50:40.308Z;summaryFields=:false:32:beginning?project=oscar-go-1

**Comment by tatianab** [comment]
We haven't seen this error for 12 days, so closing. I believe it was fixed by https://go-review.git.corp.google.com/c/oscar/+/613176.
