### ISSUE TITLE
add data source: go.dev documentation

### ISSUE THREAD

**Issue by tatianab** [golang/oscar#26]
This is already implemented and just needs to be enabled. It is (possibly) slow so we may need to figure out a way to enable it without blocking important actions from occurring in a timely manner.

Child of #25

**Comment by jba** [comment]
Have you confirmed it's slow from Cloud Run to Firestore?

**Comment by tatianab** [comment]
Crawl is now triggered by a Cloud Scheduler job once every weekday.
