### ISSUE TITLE
gerrit: clean body for related-content documents

### ISSUE THREAD

**Issue by zpavlinovic** [golang/oscar#35]
The token limit for the Gemini embedding model is 2048 (which is roughly 8200 characters), and the model will silently truncate the input to its max allowed length. Consider removing irrelevant comments, such as Trybot messages.

**Comment by zpavlinovic** [comment]
Around 7% of all CLs on the Go repo are above the Gemini token limit.

**Comment by hyangah** [comment]
This is done. Thanks @zpavlinovic
